/// Maps each recorded IPA symbol to its ASCII-safe audio filename slug.
///
/// just_audio double-percent-encodes non-ASCII asset paths on Flutter Web
/// (confirmed: a request for `æ.wav` actually fetched `%25C3%25A6.wav`,
/// which 404s through to the SPA's index.html fallback instead of the
/// audio). Recordings are stored under
/// assets/audio/phonemes/{slug}.wav using these ASCII names instead.
const Map<String, String> phonemeAudioSlugs = <String, String>{
  'iː': 'i',
  'ɪ': 'ih',
  'ɛ': 'eh',
  'æ': 'ae',
  'ɑ': 'aa',
  'ɔː': 'aw',
  'ʊ': 'uh',
  'uː': 'uw',
  'ʌ': 'ah',
  'ə': 'schwa',
  'eɪ': 'ei',
  'aɪ': 'ai',
  'aʊ': 'au',
  'ɔɪ': 'oi',
  'oʊ': 'ou',
  'ɝ': 'er',
  'ɚ': 'axr',
  'ɑr': 'aar',
  'ɛr': 'ehr',
  'ɪr': 'ihr',
  'ɔr': 'awr',
  'p': 'p',
  't': 't',
  'k': 'k',
  'tʃ': 'ch',
  'f': 'f',
  'θ': 'th',
  's': 's',
  'ʃ': 'sh',
  'b': 'b',
  'd': 'd',
  'g': 'g',
  'dʒ': 'jh',
  'v': 'v',
  'ð': 'dh',
  'z': 'z',
  'ʒ': 'zh',
  'm': 'm',
  'n': 'n',
  'ŋ': 'ng',
  'l': 'l',
  'w': 'w',
  'j': 'y',
  'h': 'h',
  'r': 'r',
  'ʔ': 'glottal',
  'ɾ': 'flap',
};
